In [32]:
import os
import pandas as pd
# get .txt document
for (dirpath,dirnames,filenames) in os.walk('day'):
    for filename in filenames:
        day = pd.read_table('day/'+filename, header=0,usecols=['Station_Id_d', 'Lat', 'Lon',
                                                   'WIN_D_Avg_2mi', 'WIN_S_Avg_2mi',
                                                         'Year','Mon','Day','Hour'],
                                                   encoding='gbk', sep='\s+')
        day['date'] = day.apply(lambda x: convert(x),axis=1)
        day['date'] = day['date'].apply(lambda x: datetime.strptime(x,'%Y-%m-%d %H-%M-%S'))
        day['date'] = day['date'].apply(lambda x: x.strftime('%Y%m%d%H'))
        hour_set = set(day['date'])

        for h in hour_set:
            day[day['date']==h].to_csv('result/'+h+'.txt',sep='\t',index=False)

In [29]:
import pandas as pd
day = pd.read_table('day/20150123.txt', header=0,usecols=['Station_Id_d', 'Lat', 'Lon',
                                                   'WIN_D_Avg_2mi', 'WIN_S_Avg_2mi',
                                                         'Year','Mon','Day','Hour'],
                                                   encoding='gbk', sep='\s+')
day['date'] = day.apply(lambda x: convert(x),axis=1)
day['date'] = day['date'].apply(lambda x: datetime.strptime(x,'%Y-%m-%d %H-%M-%S'))
day['date'] = day['date'].apply(lambda x: x.strftime('%Y%m%d%H'))
hour_set = set(day['date'])

for h in hour_set:
    day[day['date']==h].to_csv('result/'+h+'.txt',sep='\t',index=False)

In [23]:
def convert(x):
    return str(int(x['Year']))+'-'+str(int(x['Mon']))+'-' +\
str(int(x['Day']))+' '+str(int(x['Hour']))+'-00-00'

In [24]:
from datetime import datetime

In [28]:
day

,Station_Id_d,Lat,Lon,Year,Mon,Day,Hour,WIN_D_Avg_2mi,WIN_S_Avg_2mi,date
0,655405,31.02,121.64,2015,1,23,0,99,0.8,2015012300
1,655450,31.14,121.49,2015,1,23,0,133,1.3,2015012300
2,655045,31.16,121.34,2015,1,23,0,999998,999998.0,2015012300
3,655540,30.80,121.41,2015,1,23,0,999998,999998.0,2015012300
4,654954,31.27,121.57,2015,1,23,0,999998,999998.0,2015012300
5,655306,31.73,121.25,2015,1,23,0,91,1.3,2015012300
6,655801,30.82,121.49,2015,1,23,0,64,1.3,2015012300
7,655207,31.42,121.22,2015,1,23,0,0,0.0,2015012300
8,654910,31.38,121.51,2015,1,23,0,154,0.8,2015012300
9,655603,31.24,121.23,2015,1,23,0,87,0.3,2015012300
10,792324,33.97,116.49,2015,1,23,0,132,1.9,2015012300
11,792315,34.23,115.86,2015,1,23,0,205,1.6,2015012300
12,792072,35.79,114.22,2015,1,23,0,187,2.8,2015012300
13,737376,30.32,117.42,2015,1,23,0,242,1.0,2015012300
14,792060,35.61,114.11,2015,1,23,0,184,4.5,2015012300
15,792055,35.80,114.96,2015,1,23,0,178,3.6,2015012300
16,792415,34.05,114.52,2015,1,23,0,234,1.2,2015012300
17,792595,31.55,114.75,2015,1,23,0,36,0.2,2015012300
18,792613,31.96,115.69,2015,1,23,0,81,1.3,2015012300
19,792842,32.97,114.16,2015,1,23,0,171,1.9,2015012300
20,792334,34.53,115.62,2015,1,23,0,136,2.2,2015012300
21,792793,31.67,115.34,2015,1,23,0,234,2.0,2015012300
22,792015,35.72,114.75,2015,1,23,0,162,2.4,2015012300
23,792330,34.56,115.61,2015,1,23,0,158,1.3,2015012300
24,792414,33.67,114.05,2015,1,23,0,169,1.0,2015012300
25,792036,35.92,115.10,2015,1,23,0,179,3.9,2015012300
26,792333,34.41,115.63,2015,1,23,0,165,2.4,2015012300
27,792270,34.42,114.04,2015,1,23,0,230,1.0,2015012300
28,792649,35.92,114.22,2015,1,23,0,207,2.5,2015012300
29,685011,35.82,118.32,2015,1,23,0,175,0.9,2015012300
...,...,...,...,...,...,...,...,...,...,...
204389,775394,33.39,119.71,2015,1,23,21,91,2.9,2015012321
204390,709303,27.44,117.40,2015,1,23,21,356,0.0,2015012321
204391,703112,27.46,119.64,2015,1,23,21,240,1.0,2015012321
204392,703211,27.05,119.16,2015,1,23,21,75,1.1,2015012321
204393,709802,27.09,117.90,2015,1,23,21,353,2.1,2015012321
204394,709721,27.05,118.17,2015,1,23,21,170,0.3,2015012321
204395,709244,27.86,117.78,2015,1,23,21,97,7.4,2015012321
204396,703408,27.16,119.94,2015,1,23,21,0,0.0,2015012321
204397,737880,30.97,118.88,2015,1,23,21,73,1.0,2015012321
204398,738771,30.25,118.18,2015,1,23,21,144,0.4,2015012321
204399,735303,31.43,117.81,2015,1,23,21,999998,999998.0,2015012321
204400,738960,30.11,117.75,2015,1,23,21,329,0.3,2015012321
204401,733521,32.75,117.41,2015,1,23,21,999998,999998.0,2015012321
204402,738168,30.68,118.87,2015,1,23,21,196,3.1,2015012321
204403,737358,30.50,117.27,2015,1,23,21,84,0.8,2015012321
204404,737961,30.62,118.60,2015,1,23,21,999999,0.0,2015012321
204405,736467,30.92,117.04,2015,1,23,21,195,0.9,2015012321
204406,738169,30.56,118.93,2015,1,23,21,280,0.6,2015012321
204407,737754,31.06,117.94,2015,1,23,21,317,0.4,2015012321
204408,735972,30.82,118.28,2015,1,23,21,999999,0.1,2015012321
204409,731308,33.74,117.14,2015,1,23,21,999998,999998.0,2015012321
204410,737872,31.04,118.80,2015,1,23,21,44,1.1,2015012321
204411,733759,32.55,117.87,2015,1,23,21,67,2.3,2015012321
204412,737004,30.20,116.60,2015,1,23,21,999998,999998.0,2015012321
204413,732711,32.65,116.36,2015,1,23,21,999998,999998.0,2015012321
204414,736782,30.68,116.65,2015,1,23,21,999999,0.1,2015012321
204415,735060,31.94,117.50,2015,1,23,21,999998,999998.0,2015012321
204416,709727,27.31,118.70,2015,1,23,21,999998,999998.0,2015012321
204417,709907,27.49,118.18,2015,1,23,21,198,0.9,2015012321
204418,739059,29.84,118.58,2015,1,23,21,65,1.0,2015012321